### ISSUE TITLE
Update to version 1000 of the plugin interface

### ISSUE THREAD

**Issue by brachiel** [tnodir/luaplsql#1]
Since version 1000 of the plugin interface, there are new events and functions available to plugins (i.e. DE_GetConnectionInfoEx10, IDE_WindowPin, OnWindowConnectionChange, etc.)

These should be included and made available to LUA plugins.

**Comment by tnodir** [comment]
See https://github.com/tnodir/luaplsql/commit/1e2b69dd68aae42e3608c3a44591e28629017023
