### ISSUE TITLE
Menus no longer work in PL/SQL Developer 12 (due to Ribbon UI)

### ISSUE THREAD

**Issue by frankschmitt** [tnodir/luaplsql#6]
PL/SQL Developer 12 has introduced a new Ribbon-based UI. Therefore, the nice menu structure of the plugin no longer works - all functions are placed in the Ribbon group instead (see screenshot).

I'm not 100% sure how this should be handled - perhaps introduce a Ribbon sub-group for each menu? 

![image](https://cloud.githubusercontent.com/assets/553598/24787934/2e4a2eda-1b6b-11e7-843f-653c55b1dee6.png)

**Comment by tnodir** [comment]
Frank, please build from latest master.
This issue was fixed.

**Comment by frankschmitt** [comment]
My mistake - when building from latest master, it works like a charm.
Thanks for the quick response + for providing such a wonderful plugin!
